-- Seed eventi da Excel (91 eventi)
-- Esegui questo file sul tuo database Neon dopo aver fatto il migrate.
-- ATTENZIONE: esegui solo una volta o aggiungi ON CONFLICT DO NOTHING.

INSERT INTO events (name, type, effect, description) VALUES
  ('Boom Immobiliare', 'permanente', '{"type": "category_bonus", "categoryId": 2, "delta": 10}'::jsonb, 'Immobili +10'),
  ('Bolla Immobiliare', 'permanente', '{"type": "category_bonus", "categoryId": 2, "delta": -10}'::jsonb, 'Immobili -10'),
  ('Gp Monza', 'permanente', '{"type": "category_bonus", "categoryId": 1, "delta": 10}'::jsonb, 'Auto +10'),
  ('Incidente', 'permanente', '{"type": "category_bonus", "categoryId": 1, "delta": -10}'::jsonb, 'Auto -10'),
  ('Treno mare', 'permanente', '{"type": "category_bonus", "categoryId": 4, "delta": 10}'::jsonb, 'Trasporti +10'),
  ('Sud Italia', 'permanente', '{"type": "category_bonus", "categoryId": 4, "delta": -10}'::jsonb, 'Trasporti -10'),
  ('Nuovo programma', 'permanente', '{"type": "category_bonus", "categoryId": 8, "delta": 10}'::jsonb, 'Intrattenimento +10'),
  ('Scandalo Signorini', 'permanente', '{"type": "category_bonus", "categoryId": 8, "delta": -10}'::jsonb, 'Intrattenimento -10'),
  ('Rivoluzione IA', 'permanente', '{"type": "category_bonus", "categoryId": 3, "delta": 10}'::jsonb, 'Tecnologia +10'),
  ('Cyberattacco', 'permanente', '{"type": "category_bonus", "categoryId": 3, "delta": -10}'::jsonb, 'Tecnologia -10'),
  ('Mondiali', 'permanente', '{"type": "category_bonus", "categoryId": 7, "delta": 10}'::jsonb, 'Sport +10'),
  ('Scandalo Sportivo', 'permanente', '{"type": "category_bonus", "categoryId": 7, "delta": -10}'::jsonb, 'Sport -10'),
  ('Età dell''Oro', 'permanente', '{"type": "category_bonus", "categoryId": 5, "delta": 10}'::jsonb, 'Lusso +10'),
  ('Tassa sui Ricchi', 'permanente', '{"type": "category_bonus", "categoryId": 5, "delta": -10}'::jsonb, 'Lusso -10'),
  ('Energia Verde', 'permanente', '{"type": "category_bonus", "categoryId": 9, "delta": 10}'::jsonb, 'Energia +10'),
  ('Disastro Nucleare', 'permanente', '{"type": "category_bonus", "categoryId": 9, "delta": -10}'::jsonb, 'Energia -10'),
  ('Turismo Record', 'permanente', '{"type": "category_bonus", "categoryId": 12, "delta": 10}'::jsonb, 'Turismo +10'),
  ('Overtourism', 'permanente', '{"type": "category_bonus", "categoryId": 12, "delta": -10}'::jsonb, 'Turismo -10'),
  ('Campagna Elettorale', 'permanente', '{"type": "category_bonus", "categoryId": 10, "delta": 10}'::jsonb, 'Potere +10'),
  ('Scandalo Politico', 'permanente', '{"type": "category_bonus", "categoryId": 10, "delta": -10}'::jsonb, 'Potere -10'),
  ('Boom economico', 'permanente', '{"type": "category_bonus", "categoryId": 6, "delta": 10}'::jsonb, 'Imprese +10'),
  ('Crisi economica', 'permanente', '{"type": "category_bonus", "categoryId": 6, "delta": -10}'::jsonb, 'Imprese -10'),
  ('Scoperta epocale', 'permanente', '{"type": "category_bonus", "categoryId": 11, "delta": 10}'::jsonb, 'Scienza +10'),
  ('Esperimento fallito', 'permanente', '{"type": "category_bonus", "categoryId": 11, "delta": -10}'::jsonb, 'Scienza -10'),
  ('Furto al Louvre', 'permanente', '{"type": "category_bonus", "categoryId": 15, "delta": -10}'::jsonb, 'Quadri -10'),
  ('Festival dell''Arte', 'permanente', '{"type": "category_bonus", "categoryId": 15, "delta": 10}'::jsonb, 'Quadri +10'),
  ('Estinzione', 'permanente', '{"type": "category_bonus", "categoryId": 13, "delta": -10}'::jsonb, 'Animali -10'),
  ('Conservazione della Fauna', 'permanente', '{"type": "category_bonus", "categoryId": 13, "delta": 10}'::jsonb, 'Animali +10'),
  ('Bocciato all''esame', 'permanente', '{"type": "category_bonus", "categoryId": 14, "delta": -10}'::jsonb, 'Università -10'),
  ('Classifica Universitaria', 'permanente', '{"type": "category_bonus", "categoryId": 14, "delta": 10}'::jsonb, 'Università +10'),
  ('Ricerca Finanziata', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 14, "delta": 10}, {"categoryId": 11, "delta": 10}]}'::jsonb, 'Università +10 e Scienza +10'),
  ('Documentario Virale', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 13, "delta": 10}, {"categoryId": 8, "delta": 10}]}'::jsonb, 'Animali +10 e Intrattenimento +10'),
  ('Mostra Internazionale', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 15, "delta": 10}, {"categoryId": 12, "delta": 10}]}'::jsonb, 'Quadri +10 e Turismo +10'),
  ('Smart City + scuola intelligente Solaro', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 3, "delta": -10}, {"categoryId": 2, "delta": 10}, {"categoryId": 9, "delta": 10}]}'::jsonb, 'Tecnologia -10, Immobili +10, Energia +10'),
  ('Era Digitale', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 3, "delta": 15}, {"categoryId": 8, "delta": -10}]}'::jsonb, 'Tecnologia +15 e Intrattenimento -10'),
  ('Rinascimento Scientifico', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 11, "delta": 15}, {"categoryId": 3, "delta": 10}, {"categoryId": 9, "delta": 10}]}'::jsonb, 'Scienza +15, Tecnologia +10, Energia +10'),
  ('Guerra Commerciale', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 6, "delta": -10}, {"categoryId": 4, "delta": -10}, {"categoryId": 10, "delta": 10}]}'::jsonb, 'Imprese -10, Trasporti -10, Potere +10'),
  ('Esplosione del Turismo', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 12, "delta": 15}, {"categoryId": 5, "delta": 10}]}'::jsonb, 'Turismo +15 e Lusso +10'),
  ('Superlega', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 7, "delta": 15}, {"categoryId": 8, "delta": -10}]}'::jsonb, 'Sport +15 e Intrattenimento -10'),
  ('Crisi Energetica', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 9, "delta": -15}, {"categoryId": 4, "delta": -10}]}'::jsonb, 'Energia -15 e Trasporti -10'),
  ('Globalizzazione', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 6, "delta": 10}, {"categoryId": 4, "delta": 10}, {"categoryId": 12, "delta": 10}]}'::jsonb, 'Imprese +10, Trasporti +10, Turismo +10'),
  ('Età dell''Abbondanza', 'permanente', '{"type": "all_goods_bonus", "delta": 5}'::jsonb, 'Tutti i beni +5'),
  ('Crisi Globale', 'permanente', '{"type": "all_goods_bonus", "delta": -5}'::jsonb, 'Tutti i beni -5'),
  ('Mania del Collezionismo', 'permanente', '{"type": "modifier_mini_collection", "delta": 10}'::jsonb, 'Mini-Collezioni +10'),
  ('Collezionisti Internazionali', 'permanente', '{"type": "modifier_complete_collection", "delta": 15}'::jsonb, 'Collezioni Complete +15'),
  ('Mercato Frammentato', 'permanente', '{"type": "modifier_mini_collection", "multiplier": 0}'::jsonb, 'Le Mini-Collezioni non valgono punti'),
  ('Monopolio', 'permanente', '{"type": "modifier_majority", "delta": 10}'::jsonb, 'Bonus Maggioranza +10'),
  ('Imperi Economici', 'permanente', '{"type": "modifier_majority", "delta": 15}'::jsonb, 'Bonus Maggioranza +15'),
  ('Ossessione da Collezione', 'permanente', '{"type": "multi_modifier", "modifiers": [{"type": "modifier_mini_collection", "delta": 5}, {"type": "modifier_complete_collection", "delta": 10}]}'::jsonb, 'Mini-Collezioni +5 e Collezioni Complete +10'),
  ('Benefattore', 'istantaneo', '{"type": "credits_all", "delta": 20}'::jsonb, 'Tutti guadagnano 20 crediti'),
  ('Recessione', 'istantaneo', '{"type": "credits_all", "delta": -20}'::jsonb, 'Tutti perdono 20 crediti'),
  ('Bonus Governativo', 'istantaneo', '{"type": "credits_all", "delta": 30}'::jsonb, 'Tutti guadagnano 30 crediti'),
  ('Stretta Fiscale', 'istantaneo', '{"type": "credits_all", "delta": -30}'::jsonb, 'Tutti perdono 30 crediti'),
  ('Inflazione', 'permanente', '{"type": "credits_multiplier", "multiplier": 0.5}'::jsonb, 'I crediti finali valgono metà'),
  ('Deflazione', 'permanente', '{"type": "credits_multiplier", "multiplier": 2}'::jsonb, 'I crediti finali valgono il doppio'),
  ('Categoria del Momento', 'permanente', '{"type": "random_category_bonus", "delta": 15}'::jsonb, 'Una categoria casuale vale +15'),
  ('Categoria Dimenticata', 'permanente', '{"type": "random_category_bonus", "delta": -15}'::jsonb, 'Una categoria casuale vale -15'),
  ('Mania Collettiva', 'permanente', '{"type": "random_category_multiplier", "multiplier": 2}'::jsonb, 'Una categoria casuale vale il doppio'),
  ('Crollo Improvviso', 'permanente', '{"type": "random_category_multiplier", "multiplier": 0.5}'::jsonb, 'Una categoria casuale vale metà'),
  ('Bolla Speculativa', 'permanente', '{"type": "goods_by_value", "condition": "gte", "threshold": 25, "delta": 10}'::jsonb, 'Tutti i beni da 25+ punti valgono +10'),
  ('Caccia all''Affare', 'permanente', '{"type": "goods_by_value", "condition": "lte", "threshold": 15, "delta": 10}'::jsonb, 'Tutti i beni da 15 o meno valgono +10'),
  ('Mercato di Lusso', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 5, "delta": 10}, {"categoryId": 12, "delta": 10}]}'::jsonb, 'Lusso e Turismo +10'),
  ('Industrializzazione', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 6, "delta": 10}, {"categoryId": 9, "delta": 10}]}'::jsonb, 'Imprese ed Energia +10'),
  ('Innovazione Tecnologica fallita', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 3, "delta": -10}, {"categoryId": 11, "delta": -10}]}'::jsonb, 'Tecnologia -10 Scienza -10'),
  ('Nuova Frontiera', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 12, "delta": 10}, {"categoryId": 11, "delta": 10}, {"categoryId": 9, "delta": 10}]}'::jsonb, 'Turismo, Scienza ed Energia +10'),
  ('Rivoluzione Sociale', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 10, "delta": -15}, {"categoryId": 12, "delta": 15}]}'::jsonb, 'Potere -15 e Turismo +15'),
  ('Scoperta scheletro dinosauro', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 11, "delta": 10}, {"categoryId": 13, "delta": 15}]}'::jsonb, 'Scienza +10 e Animali +15'),
  ('Beni Rifugio', 'permanente', '{"type": "goods_by_value", "condition": "lte", "threshold": 20, "delta": 15}'::jsonb, 'Tutti i beni da 20 punti o meno valgono +15'),
  ('Caccia al Lusso', 'permanente', '{"type": "goods_by_value", "condition": "gte", "threshold": 25, "delta": 15}'::jsonb, 'Tutti i beni da 25 punti o più valgono +15'),
  ('Re dei Collezionisti', 'permanente', '{"type": "modifier_complete_collection", "delta": 25}'::jsonb, 'Le Collezioni Complete valgono +25 aggiuntivi'),
  ('Guerra dei Monopoli', 'permanente', '{"type": "modifier_majority", "multiplier": 2}'::jsonb, 'Le Maggioranze valgono il doppio'),
  ('Nuovo Ordine Mondiale', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 10, "delta": 20}, {"categoryId": 6, "delta": 10}]}'::jsonb, 'Potere +20 e Imprese +10'),
  ('Ferrari campione F1', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 1, "delta": 20}, {"categoryId": 8, "delta": 10}]}'::jsonb, 'Auto +20 e Intrattenimento +10'),
  ('Età delle Esplorazioni', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 12, "delta": 20}, {"categoryId": 4, "delta": 10}]}'::jsonb, 'Turismo +20 e Trasporti +10'),
  ('Olimpiadi Globali', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 7, "delta": 20}, {"categoryId": 12, "delta": 10}, {"categoryId": 8, "delta": 10}]}'::jsonb, 'Sport +20, Turismo +10 e Intrattenimento +10'),
  ('Bolla dei Social', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 8, "delta": -20}, {"categoryId": 5, "delta": 10}]}'::jsonb, 'Intrattenimento -20 e Lusso +10'),
  ('Abbandono animali', 'permanente', '{"type": "multi_category_bonus", "deltas": [{"categoryId": 13, "delta": -20}, {"categoryId": 12, "delta": 10}]}'::jsonb, 'Animali -20 e Turismo +10'),
  ('Cambio di Priorità', 'permanente', '{"type": "modifier_complete_collection", "multiplier": 0}'::jsonb, 'Le Collezioni Complete non valgono più punti'),
  ('Mercato Impazzito', 'permanente', '{"type": "modifier_majority", "multiplier": 0}'::jsonb, 'Le Maggioranze non valgono più punti'),
  ('Era dei Collezionisti', 'permanente', '{"type": "mini_collection_equals_complete"}'::jsonb, 'Le Mini-Collezioni valgono quanto le Complete'),
  ('Grande Fusione', 'permanente', '{"type": "merge_categories_majority", "categoryIds": [1, 4]}'::jsonb, 'Auto e Trasporti sono una sola categoria per le Maggioranze'),
  ('Rinascimento Culturale', 'permanente', '{"type": "merge_categories_majority", "categoryIds": [14, 15]}'::jsonb, 'Università e Quadri sono una sola categoria per le Maggioranze'),
  ('Crisi di Fiducia', 'permanente', '{"type": "credits_multiplier", "multiplier": 0}'::jsonb, 'I crediti finali non valgono punti'),
  ('Banche Centrali', 'permanente', '{"type": "credits_multiplier", "multiplier": 2}'::jsonb, 'I crediti finali valgono il doppio'),
  ('Pioggia di Liquidità', 'istantaneo', '{"type": "credits_all", "delta": 50}'::jsonb, 'Tutti ricevono 50 crediti'),
  ('Grande Recessione', 'istantaneo', '{"type": "credits_all", "delta": -50}'::jsonb, 'Tutti perdono 50 crediti'),
  ('Tassa Patrimoniale', 'istantaneo', '{"type": "credits_conditional", "condition": "above", "threshold": 40, "delta": -20}'::jsonb, 'Chi ha oltre 40 crediti perde 20 crediti'),
  ('Incentivi Statali', 'istantaneo', '{"type": "credits_conditional", "condition": "below", "threshold": 20, "delta": 20}'::jsonb, 'Chi ha meno di 20 crediti guadagna 20 crediti'),
  ('Bene Misterioso', 'segreto', '{"type": "random_category_bonus_secret", "delta": 20}'::jsonb, 'Categoria casuale +20 rivelata a fine partita'),
  ('Investimento Segreto', 'segreto', '{"type": "random_category_multiplier_secret", "multiplier": 2}'::jsonb, 'Categoria casuale x2 rivelata a fine partita'),
  ('Mercato Nero', 'segreto', '{"type": "random_category_multiplier_secret", "multiplier": 0.5}'::jsonb, 'Categoria casuale dimezzata rivelata a fine partita');
